version: 2
updates:
  - package-ecosystem: "gomod"
    directory: "/"
    schedule:
      interval: "weekly"
    labels:
      - "dependencies"
      - "go"

  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "weekly"
    labels:
      - "dependencies"
      - "javascript"

  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "monthly"
    groups:
      codeql-version-updates:
        applies-to: version-updates
        patterns:
          - "github/codeql-action*"
      codeql-security-updates:
        applies-to: security-updates
        patterns:
          - "github/codeql-action*"

  - package-ecosystem: "docker"
    directory: "/"
    schedule:
      interval: "weekly"

  - package-ecosystem: "docker"
    directory: "/addons/ollama-init"
    schedule:
      interval: "weekly"
