// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.1
// - protoc             v6.31.1
// source: scalper.proto

package proto

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	ScalperService_Scan_FullMethodName     = "/scalper.ScalperService/Scan"
	ScalperService_Backfill_FullMethodName = "/scalper.ScalperService/Backfill"
	ScalperService_Health_FullMethodName   = "/scalper.ScalperService/Health"
)

// ScalperServiceClient is the client API for ScalperService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type ScalperServiceClient interface {
	Scan(ctx context.Context, in *ScanRequest, opts ...grpc.CallOption) (*ScanResponse, error)
	Backfill(ctx context.Context, in *BackfillRequest, opts ...grpc.CallOption) (*BackfillResponse, error)
	Health(ctx context.Context, in *HealthRequest, opts ...grpc.CallOption) (*HealthResponse, error)
}

type scalperServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewScalperServiceClient(cc grpc.ClientConnInterface) ScalperServiceClient {
	return &scalperServiceClient{cc}
}

func (c *scalperServiceClient) Scan(ctx context.Context, in *ScanRequest, opts ...grpc.CallOption) (*ScanResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ScanResponse)
	err := c.cc.Invoke(ctx, ScalperService_Scan_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *scalperServiceClient) Backfill(ctx context.Context, in *BackfillRequest, opts ...grpc.CallOption) (*BackfillResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(BackfillResponse)
	err := c.cc.Invoke(ctx, ScalperService_Backfill_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *scalperServiceClient) Health(ctx context.Context, in *HealthRequest, opts ...grpc.CallOption) (*HealthResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(HealthResponse)
	err := c.cc.Invoke(ctx, ScalperService_Health_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// ScalperServiceServer is the server API for ScalperService service.
// All implementations must embed UnimplementedScalperServiceServer
// for forward compatibility.
type ScalperServiceServer interface {
	Scan(context.Context, *ScanRequest) (*ScanResponse, error)
	Backfill(context.Context, *BackfillRequest) (*BackfillResponse, error)
	Health(context.Context, *HealthRequest) (*HealthResponse, error)
	mustEmbedUnimplementedScalperServiceServer()
}

// UnimplementedScalperServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedScalperServiceServer struct{}

func (UnimplementedScalperServiceServer) Scan(context.Context, *ScanRequest) (*ScanResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Scan not implemented")
}
func (UnimplementedScalperServiceServer) Backfill(context.Context, *BackfillRequest) (*BackfillResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Backfill not implemented")
}
func (UnimplementedScalperServiceServer) Health(context.Context, *HealthRequest) (*HealthResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Health not implemented")
}
func (UnimplementedScalperServiceServer) mustEmbedUnimplementedScalperServiceServer() {}
func (UnimplementedScalperServiceServer) testEmbeddedByValue()                        {}

// UnsafeScalperServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to ScalperServiceServer will
// result in compilation errors.
type UnsafeScalperServiceServer interface {
	mustEmbedUnimplementedScalperServiceServer()
}

func RegisterScalperServiceServer(s grpc.ServiceRegistrar, srv ScalperServiceServer) {
	// If the following call panics, it indicates UnimplementedScalperServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&ScalperService_ServiceDesc, srv)
}

func _ScalperService_Scan_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ScanRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ScalperServiceServer).Scan(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ScalperService_Scan_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ScalperServiceServer).Scan(ctx, req.(*ScanRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ScalperService_Backfill_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(BackfillRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ScalperServiceServer).Backfill(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ScalperService_Backfill_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ScalperServiceServer).Backfill(ctx, req.(*BackfillRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ScalperService_Health_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(HealthRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ScalperServiceServer).Health(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ScalperService_Health_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ScalperServiceServer).Health(ctx, req.(*HealthRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// ScalperService_ServiceDesc is the grpc.ServiceDesc for ScalperService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var ScalperService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "scalper.ScalperService",
	HandlerType: (*ScalperServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Scan",
			Handler:    _ScalperService_Scan_Handler,
		},
		{
			MethodName: "Backfill",
			Handler:    _ScalperService_Backfill_Handler,
		},
		{
			MethodName: "Health",
			Handler:    _ScalperService_Health_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "scalper.proto",
}
